import 'express-async-errors';
import express from 'express';
import path from 'path';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { fileURLToPath } from 'url';
import { pool, tx } from './scripts/db.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000);
const JWT_SECRET=process.env.JWT_SECRET||'change-this-development-secret';
const APP_NAME=process.env.APP_NAME||'ACIS POS';
const TRIAL_DAYS=Math.max(1,Number(process.env.DEFAULT_TRIAL_DAYS||14));
const app=express();
app.use(express.json({limit:'2mb'}));
app.use(express.static(path.join(__dirname,'public')));

const n=v=>Number(v||0), now=()=>new Date().toISOString();
const code=(prefix)=>`${prefix}-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;
const camelProduct=r=>({id:r.id,sku:r.sku,barcode:r.barcode,name:r.name,categoryId:r.category_id,unitId:r.unit_id,cost:n(r.cost),price:n(r.price),stock:n(r.stock),minStock:n(r.min_stock),active:r.active});
const camelPartner=r=>({id:r.id,code:r.code,type:r.type,name:r.name,phone:r.phone,email:r.email,address:r.address,points:n(r.points)});
const camelSale=r=>({id:r.id,invoice:r.invoice,createdAt:r.created_at,cashier:r.cashier_name,customerId:r.customer_id||'',paymentMethod:r.payment_method,subtotal:n(r.subtotal),discount:n(r.discount),total:n(r.total),paid:n(r.paid),costTotal:n(r.cost_total),pointsEarned:n(r.points_earned),status:r.status,items:r.items||[]});
const camelPurchase=r=>({id:r.id,number:r.number,supplierId:r.supplier_id||'',createdAt:r.created_at,total:n(r.total),status:r.status,note:r.note,items:r.items||[]});

async function audit(ctx,action,entity,detail=''){
  await pool.query(`INSERT INTO audit_logs(tenant_id,outlet_id,user_id,username,action,entity,detail) VALUES($1,$2,$3,$4,$5,$6,$7)`,[ctx?.tenantId||null,ctx?.outletId||null,ctx?.user?.id||null,ctx?.user?.username||'system',action,entity,String(detail||'')]);
}

async function auth(req,res,next){
  try{
    const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');
    const p=jwt.verify(token,JWT_SECRET);
    const user=(await pool.query(`SELECT id,name,username,email,active,is_platform_admin,created_at FROM users WHERE id=$1 AND active=true`,[p.sub])).rows[0];
    if(!user) throw new Error('user');
    const membership=(await pool.query(`SELECT tu.tenant_id,tu.default_outlet_id,tu.active,r.name role,r.permissions,t.name tenant_name,t.status tenant_status
      FROM tenant_users tu JOIN tenants t ON t.id=tu.tenant_id LEFT JOIN roles r ON r.id=tu.role_id
      WHERE tu.user_id=$1 AND tu.tenant_id=$2 AND tu.active=true`,[user.id,p.tenantId])).rows[0];
    if(!membership) throw new Error('tenant');
    const outletId=p.outletId||membership.default_outlet_id;
    const outlet=(await pool.query(`SELECT id,name,code,active FROM outlets WHERE id=$1 AND tenant_id=$2 AND active=true`,[outletId,membership.tenant_id])).rows[0];
    if(!outlet) throw new Error('outlet');
    const sub=(await pool.query(`SELECT s.status,s.expires_at,s.grace_until,sp.code plan_code,sp.name plan_name,sp.max_outlets,sp.max_users
      FROM subscriptions s JOIN subscription_plans sp ON sp.id=s.plan_id WHERE s.tenant_id=$1 ORDER BY s.created_at DESC LIMIT 1`,[membership.tenant_id])).rows[0]||null;
    req.ctx={user,tenantId:membership.tenant_id,tenantName:membership.tenant_name,outletId:outlet.id,outletName:outlet.name,role:membership.role||'User',permissions:membership.permissions||[],subscription:sub};
    next();
  }catch{return res.status(401).json({error:'Sesi tidak valid. Silakan login kembali.'})}
}
function platformAdmin(req,res,next){if(!req.ctx.user.is_platform_admin)return res.status(403).json({error:'Akses platform admin diperlukan.'});next()}
function activeSubscription(req,res,next){const s=req.ctx.subscription;if(!s)return res.status(402).json({error:'Langganan belum aktif.'});const deadline=new Date(s.grace_until||s.expires_at);if(['cancelled','suspended'].includes(s.status)||deadline<new Date())return res.status(402).json({error:'Langganan ACIS POS telah berakhir. Silakan perpanjang untuk melanjutkan transaksi.'});next()}
const safeUser=(u,ctx)=>({id:u.id,name:u.name,username:u.username,email:u.email||'',role:ctx.role,active:u.active,createdAt:u.created_at,tenant:{id:ctx.tenantId,name:ctx.tenantName},outlet:{id:ctx.outletId,name:ctx.outletName},subscription:ctx.subscription,isPlatformAdmin:u.is_platform_admin});

app.get('/api/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({status:'ok',app:APP_NAME,version:'2.0.0',database:'postgresql',multiTenant:true,time:now()})}catch(e){res.status(503).json({status:'error',database:'unavailable'})}});

app.post('/api/login',async(req,res)=>{
  const {username,password,tenantId,outletId}=req.body||{};
  const u=(await pool.query(`SELECT * FROM users WHERE username=$1 AND active=true`,[String(username||'')])).rows[0];
  if(!u||!await bcrypt.compare(String(password||''),u.password_hash))return res.status(401).json({error:'Username atau password salah.'});
  const memberships=(await pool.query(`SELECT tu.tenant_id,tu.default_outlet_id,t.name tenant_name,r.name role,o.name outlet_name
    FROM tenant_users tu JOIN tenants t ON t.id=tu.tenant_id LEFT JOIN roles r ON r.id=tu.role_id LEFT JOIN outlets o ON o.id=tu.default_outlet_id
    WHERE tu.user_id=$1 AND tu.active=true AND t.status='active' ORDER BY t.name`,[u.id])).rows;
  if(!memberships.length)return res.status(403).json({error:'User belum terhubung ke bisnis aktif.'});
  const m=memberships.find(x=>x.tenant_id===tenantId)||memberships[0];
  const selectedOutlet=outletId||m.default_outlet_id;
  const token=jwt.sign({sub:u.id,tenantId:m.tenant_id,outletId:selectedOutlet},JWT_SECRET,{expiresIn:'12h'});
  res.json({token,user:{id:u.id,name:u.name,username:u.username,role:m.role,tenant:{id:m.tenant_id,name:m.tenant_name},outlet:{id:selectedOutlet,name:m.outlet_name}},memberships});
});

app.post('/api/onboarding/register',async(req,res)=>{
  const b=req.body||{}; if(!b.businessName||!b.name||!b.username||!b.password)return res.status(400).json({error:'Nama bisnis, nama owner, username dan password wajib diisi.'});
  try{
    const out=await tx(async c=>{
      if((await c.query(`SELECT 1 FROM users WHERE username=$1`,[b.username])).rowCount)throw Object.assign(new Error('Username sudah digunakan.'),{status:409});
      const tenant=(await c.query(`INSERT INTO tenants(code,name) VALUES($1,$2) RETURNING *`,[String(b.businessCode||code('BIZ')).toUpperCase(),b.businessName])).rows[0];
      const outlet=(await c.query(`INSERT INTO outlets(tenant_id,code,name,address) VALUES($1,'MAIN',$2,$3) RETURNING *`,[tenant.id,b.outletName||'Toko Utama',b.address||''])).rows[0];
      const hash=await bcrypt.hash(String(b.password),10);
      const user=(await c.query(`INSERT INTO users(name,username,email,password_hash) VALUES($1,$2,$3,$4) RETURNING id,name,username,email`,[b.name,b.username,b.email||null,hash])).rows[0];
      const roles={}; for(const [name,permissions] of [['Administrator',['*']],['Kasir',['pos','sales.view','products.view']],['Manager',['dashboard','pos','products','inventory','purchases','sales','partners','reports']]])roles[name]=(await c.query(`INSERT INTO roles(tenant_id,name,permissions) VALUES($1,$2,$3::jsonb) RETURNING id`,[tenant.id,name,JSON.stringify(permissions)])).rows[0].id;
      await c.query(`INSERT INTO tenant_users(tenant_id,user_id,role_id,default_outlet_id) VALUES($1,$2,$3,$4)`,[tenant.id,user.id,roles.Administrator,outlet.id]);
      await c.query(`INSERT INTO tenant_settings(tenant_id,company_name,address,email) VALUES($1,$2,$3,$4)`,[tenant.id,b.businessName,b.address||'',b.email||'']);
      const plan=(await c.query(`SELECT id FROM subscription_plans WHERE code=$1`,[b.planCode||'STARTER'])).rows[0]||(await c.query(`SELECT id FROM subscription_plans WHERE active=true ORDER BY price_monthly LIMIT 1`)).rows[0];
      await c.query(`INSERT INTO subscriptions(tenant_id,plan_id,status,expires_at) VALUES($1,$2,'trial',now()+($3::int * interval '1 day'))`,[tenant.id,plan.id,String(TRIAL_DAYS)]);
      for(const x of ['Makanan','Minuman','Lainnya'])await c.query(`INSERT INTO categories(tenant_id,name) VALUES($1,$2)`,[tenant.id,x]);
      for(const x of ['Pcs','Box','Botol'])await c.query(`INSERT INTO units(tenant_id,name) VALUES($1,$2)`,[tenant.id,x]);
      await c.query(`INSERT INTO partners(tenant_id,code,type,name) VALUES($1,'CUST-001','customer','Pelanggan Umum'),($1,'SUP-001','supplier','Supplier Utama')`,[tenant.id]);
      return {tenant,outlet,user};
    });
    res.status(201).json({ok:true,trialDays:TRIAL_DAYS,...out});
  }catch(e){res.status(e.status||400).json({error:e.message||'Onboarding gagal.'})}
});

app.get('/api/me',auth,(req,res)=>res.json({user:safeUser(req.ctx.user,req.ctx)}));
app.get('/api/outlets',auth,async(req,res)=>res.json({items:(await pool.query(`SELECT id,code,name,address,active FROM outlets WHERE tenant_id=$1 ORDER BY name`,[req.ctx.tenantId])).rows}));
app.post('/api/session/outlet',auth,async(req,res)=>{const o=(await pool.query(`SELECT id,name FROM outlets WHERE id=$1 AND tenant_id=$2 AND active=true`,[req.body.outletId,req.ctx.tenantId])).rows[0];if(!o)return res.status(404).json({error:'Outlet tidak ditemukan.'});const token=jwt.sign({sub:req.ctx.user.id,tenantId:req.ctx.tenantId,outletId:o.id},JWT_SECRET,{expiresIn:'12h'});res.json({token,outlet:o})});

app.get('/api/master',auth,async(req,res)=>{
 const [cats,units,roles,outlets]=await Promise.all([
  pool.query(`SELECT id,name FROM categories WHERE tenant_id=$1 AND active=true ORDER BY name`,[req.ctx.tenantId]),
  pool.query(`SELECT id,name FROM units WHERE tenant_id=$1 AND active=true ORDER BY name`,[req.ctx.tenantId]),
  pool.query(`SELECT id,name,permissions FROM roles WHERE tenant_id=$1 ORDER BY name`,[req.ctx.tenantId]),
  pool.query(`SELECT id,name,code,active FROM outlets WHERE tenant_id=$1 ORDER BY name`,[req.ctx.tenantId])]);
 res.json({categories:cats.rows,units:units.rows,roles:roles.rows,warehouses:outlets.rows,outlets:outlets.rows});
});

app.get('/api/products',auth,async(req,res)=>{const qv=`%${String(req.query.q||'')}%`;const rows=(await pool.query(`SELECT p.*,COALESCE(sb.quantity,0) stock FROM products p LEFT JOIN stock_balances sb ON sb.product_id=p.id AND sb.tenant_id=p.tenant_id AND sb.outlet_id=$2 WHERE p.tenant_id=$1 AND ($3='%%' OR p.name ILIKE $3 OR p.sku ILIKE $3 OR p.barcode ILIKE $3) ORDER BY p.created_at DESC`,[req.ctx.tenantId,req.ctx.outletId,qv])).rows;res.json({items:rows.map(camelProduct)})});
app.post('/api/products',auth,activeSubscription,async(req,res)=>{const b=req.body||{};if(!b.name||!b.sku)return res.status(400).json({error:'Nama dan SKU wajib diisi.'});try{const p=await tx(async c=>{const r=(await c.query(`INSERT INTO products(tenant_id,sku,barcode,name,category_id,unit_id,cost,price,min_stock,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[req.ctx.tenantId,b.sku,b.barcode||'',b.name,b.categoryId||null,b.unitId||null,n(b.cost),n(b.price),n(b.minStock),b.active!==false])).rows[0];const stock=n(b.stock);await c.query(`INSERT INTO stock_balances(tenant_id,outlet_id,product_id,quantity) VALUES($1,$2,$3,$4)`,[req.ctx.tenantId,req.ctx.outletId,r.id,stock]);if(stock)await c.query(`INSERT INTO stock_ledger(tenant_id,outlet_id,product_id,type,qty_in,balance,reference,note,user_id) VALUES($1,$2,$3,'opening',$4,$4,'OPENING','Stok awal',$5)`,[req.ctx.tenantId,req.ctx.outletId,r.id,stock,req.ctx.user.id]);return {...r,stock}});await audit(req.ctx,'CREATE','product',p.sku);res.json(camelProduct(p))}catch(e){if(e.code==='23505')return res.status(409).json({error:'SKU sudah digunakan di bisnis ini.'});throw e}});
app.put('/api/products/:id',auth,activeSubscription,async(req,res)=>{const b=req.body||{};const out=await tx(async c=>{const old=(await c.query(`SELECT p.*,COALESCE(sb.quantity,0) stock FROM products p LEFT JOIN stock_balances sb ON sb.product_id=p.id AND sb.outlet_id=$3 WHERE p.id=$1 AND p.tenant_id=$2 FOR UPDATE OF p`,[req.params.id,req.ctx.tenantId,req.ctx.outletId])).rows[0];if(!old)return null;const nextStock=n(b.stock??old.stock);const r=(await c.query(`UPDATE products SET sku=$3,barcode=$4,name=$5,category_id=$6,unit_id=$7,cost=$8,price=$9,min_stock=$10,active=$11,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING *`,[old.id,req.ctx.tenantId,b.sku??old.sku,b.barcode??old.barcode,b.name??old.name,b.categoryId??old.category_id,b.unitId??old.unit_id,n(b.cost??old.cost),n(b.price??old.price),n(b.minStock??old.min_stock),b.active??old.active])).rows[0];const delta=nextStock-n(old.stock);await c.query(`INSERT INTO stock_balances(tenant_id,outlet_id,product_id,quantity) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,outlet_id,product_id) DO UPDATE SET quantity=$4,updated_at=now()`,[req.ctx.tenantId,req.ctx.outletId,old.id,nextStock]);if(delta)await c.query(`INSERT INTO stock_ledger(tenant_id,outlet_id,product_id,type,qty_in,qty_out,balance,reference,note,user_id) VALUES($1,$2,$3,'adjustment',$4,$5,$6,'MANUAL','Edit stok manual',$7)`,[req.ctx.tenantId,req.ctx.outletId,old.id,Math.max(0,delta),Math.max(0,-delta),nextStock,req.ctx.user.id]);return {...r,stock:nextStock}});if(!out)return res.status(404).json({error:'Produk tidak ditemukan.'});await audit(req.ctx,'UPDATE','product',out.sku);res.json(camelProduct(out))});
app.delete('/api/products/:id',auth,activeSubscription,async(req,res)=>{const r=await pool.query(`UPDATE products SET active=false,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING sku`,[req.params.id,req.ctx.tenantId]);if(!r.rowCount)return res.status(404).json({error:'Produk tidak ditemukan.'});await audit(req.ctx,'DEACTIVATE','product',r.rows[0].sku);res.json({ok:true})});

app.get('/api/partners',auth,async(req,res)=>{const args=[req.ctx.tenantId];let sql=`SELECT * FROM partners WHERE tenant_id=$1`;if(req.query.type){args.push(req.query.type);sql+=` AND type=$2`}sql+=` ORDER BY created_at DESC`;res.json({items:(await pool.query(sql,args)).rows.map(camelPartner)})});
app.post('/api/partners',auth,activeSubscription,async(req,res)=>{const b=req.body||{};const r=(await pool.query(`INSERT INTO partners(tenant_id,code,type,name,phone,email,address) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.ctx.tenantId,b.code||code('PTN'),b.type||'customer',b.name||'Tanpa Nama',b.phone||'',b.email||'',b.address||''])).rows[0];await audit(req.ctx,'CREATE','partner',r.code);res.json(camelPartner(r))});
app.put('/api/partners/:id',auth,activeSubscription,async(req,res)=>{const b=req.body||{};const old=(await pool.query(`SELECT * FROM partners WHERE id=$1 AND tenant_id=$2`,[req.params.id,req.ctx.tenantId])).rows[0];if(!old)return res.status(404).json({error:'Partner tidak ditemukan.'});const r=(await pool.query(`UPDATE partners SET code=$3,type=$4,name=$5,phone=$6,email=$7,address=$8 WHERE id=$1 AND tenant_id=$2 RETURNING *`,[old.id,req.ctx.tenantId,b.code??old.code,b.type??old.type,b.name??old.name,b.phone??old.phone,b.email??old.email,b.address??old.address])).rows[0];await audit(req.ctx,'UPDATE','partner',r.code);res.json(camelPartner(r))});

app.get('/api/stock-ledger',auth,async(req,res)=>{const args=[req.ctx.tenantId,req.ctx.outletId];let sql=`SELECT id,at,product_id,type,qty_in,qty_out,balance,reference,note FROM stock_ledger WHERE tenant_id=$1 AND outlet_id=$2`;if(req.query.productId){args.push(req.query.productId);sql+=` AND product_id=$3`}sql+=` ORDER BY at DESC LIMIT 1000`;res.json({items:(await pool.query(sql,args)).rows.map(x=>({id:x.id,at:x.at,productId:x.product_id,type:x.type,qtyIn:n(x.qty_in),qtyOut:n(x.qty_out),balance:n(x.balance),reference:x.reference,note:x.note}))})});
app.post('/api/stock-adjustments',auth,activeSubscription,async(req,res)=>{const {productId,quantity,note}=req.body||{};const delta=n(quantity);try{const out=await tx(async c=>{const p=(await c.query(`SELECT id,sku,name FROM products WHERE id=$1 AND tenant_id=$2 AND active=true`,[productId,req.ctx.tenantId])).rows[0];if(!p)return null;const b=(await c.query(`SELECT quantity FROM stock_balances WHERE tenant_id=$1 AND outlet_id=$2 AND product_id=$3 FOR UPDATE`,[req.ctx.tenantId,req.ctx.outletId,p.id])).rows[0]||{quantity:0};const next=n(b.quantity)+delta;if(next<0)throw Object.assign(new Error('Stok tidak boleh negatif.'),{status:400});await c.query(`INSERT INTO stock_balances(tenant_id,outlet_id,product_id,quantity) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,outlet_id,product_id) DO UPDATE SET quantity=$4,updated_at=now()`,[req.ctx.tenantId,req.ctx.outletId,p.id,next]);await c.query(`INSERT INTO stock_ledger(tenant_id,outlet_id,product_id,type,qty_in,qty_out,balance,reference,note,user_id) VALUES($1,$2,$3,'adjustment',$4,$5,$6,$7,$8,$9)`,[req.ctx.tenantId,req.ctx.outletId,p.id,Math.max(0,delta),Math.max(0,-delta),next,code('ADJ'),note||'Penyesuaian stok',req.ctx.user.id]);return {...p,stock:next}});if(!out)return res.status(404).json({error:'Produk tidak ditemukan.'});await audit(req.ctx,'ADJUST','stock',`${out.sku} ${delta}`);res.json(out)}catch(e){res.status(e.status||400).json({error:e.message})}});

async function purchaseWithItems(id,ctx){const r=(await pool.query(`SELECT p.*,COALESCE(json_agg(json_build_object('productId',pi.product_id,'name',pi.name,'qty',pi.qty,'cost',pi.cost,'subtotal',pi.subtotal)) FILTER(WHERE pi.id IS NOT NULL),'[]') items FROM purchases p LEFT JOIN purchase_items pi ON pi.purchase_id=p.id AND pi.tenant_id=p.tenant_id WHERE p.id=$1 AND p.tenant_id=$2 GROUP BY p.id`,[id,ctx.tenantId])).rows[0];return r?camelPurchase(r):null}
app.get('/api/purchases',auth,async(req,res)=>{const rows=(await pool.query(`SELECT p.*,COALESCE(json_agg(json_build_object('productId',pi.product_id,'name',pi.name,'qty',pi.qty,'cost',pi.cost,'subtotal',pi.subtotal)) FILTER(WHERE pi.id IS NOT NULL),'[]') items FROM purchases p LEFT JOIN purchase_items pi ON pi.purchase_id=p.id AND pi.tenant_id=p.tenant_id WHERE p.tenant_id=$1 AND p.outlet_id=$2 GROUP BY p.id ORDER BY p.created_at DESC LIMIT 500`,[req.ctx.tenantId,req.ctx.outletId])).rows;res.json({items:rows.map(camelPurchase)})});
app.post('/api/purchases',auth,activeSubscription,async(req,res)=>{const b=req.body||{};if(!Array.isArray(b.items)||!b.items.length)return res.status(400).json({error:'Item pembelian kosong.'});const id=await tx(async c=>{const number=code('PUR');const po=(await c.query(`INSERT INTO purchases(tenant_id,outlet_id,number,supplier_id,status,note) VALUES($1,$2,$3,$4,'posted',$5) RETURNING id`,[req.ctx.tenantId,req.ctx.outletId,number,b.supplierId||null,b.note||''])).rows[0];let total=0;for(const it of b.items){const p=(await c.query(`SELECT * FROM products WHERE id=$1 AND tenant_id=$2 AND active=true`,[it.productId,req.ctx.tenantId])).rows[0];if(!p)continue;const qty=n(it.qty),cost=n(it.cost??p.cost),sub=qty*cost;total+=sub;await c.query(`INSERT INTO purchase_items(tenant_id,purchase_id,product_id,name,qty,cost,subtotal) VALUES($1,$2,$3,$4,$5,$6,$7)`,[req.ctx.tenantId,po.id,p.id,p.name,qty,cost,sub]);const bal=(await c.query(`INSERT INTO stock_balances(tenant_id,outlet_id,product_id,quantity) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,outlet_id,product_id) DO UPDATE SET quantity=stock_balances.quantity+$4,updated_at=now() RETURNING quantity`,[req.ctx.tenantId,req.ctx.outletId,p.id,qty])).rows[0];await c.query(`UPDATE products SET cost=$3,updated_at=now() WHERE id=$1 AND tenant_id=$2`,[p.id,req.ctx.tenantId,cost]);await c.query(`INSERT INTO stock_ledger(tenant_id,outlet_id,product_id,type,qty_in,balance,reference,note,user_id) VALUES($1,$2,$3,'purchase',$4,$5,$6,'Pembelian',$7)`,[req.ctx.tenantId,req.ctx.outletId,p.id,qty,bal.quantity,number,req.ctx.user.id])}await c.query(`UPDATE purchases SET total=$2 WHERE id=$1`,[po.id,total]);return po.id});const out=await purchaseWithItems(id,req.ctx);await audit(req.ctx,'CREATE','purchase',out.number);res.json(out)});
app.put('/api/purchases/:id',auth,activeSubscription,async(req,res)=>{const b=req.body||{};const r=(await pool.query(`UPDATE purchases SET supplier_id=COALESCE($3,supplier_id),note=COALESCE($4,note),status=COALESCE($5,status) WHERE id=$1 AND tenant_id=$2 RETURNING number`,[req.params.id,req.ctx.tenantId,b.supplierId||null,b.note??null,b.status??null])).rows[0];if(!r)return res.status(404).json({error:'Pembelian tidak ditemukan.'});await audit(req.ctx,'UPDATE','purchase',r.number);res.json(await purchaseWithItems(req.params.id,req.ctx))});
app.delete('/api/purchases/:id',auth,activeSubscription,async(req,res)=>{try{const number=await tx(async c=>{const po=(await c.query(`SELECT * FROM purchases WHERE id=$1 AND tenant_id=$2 AND outlet_id=$3 FOR UPDATE`,[req.params.id,req.ctx.tenantId,req.ctx.outletId])).rows[0];if(!po)return null;const items=(await c.query(`SELECT * FROM purchase_items WHERE purchase_id=$1 AND tenant_id=$2`,[po.id,req.ctx.tenantId])).rows;for(const it of items){const bal=(await c.query(`SELECT quantity FROM stock_balances WHERE tenant_id=$1 AND outlet_id=$2 AND product_id=$3 FOR UPDATE`,[req.ctx.tenantId,req.ctx.outletId,it.product_id])).rows[0];if(n(bal?.quantity)<n(it.qty))throw Object.assign(new Error(`Pembelian tidak dapat dihapus karena stok ${it.name} sudah terpakai.`),{status:409})}for(const it of items){const bal=(await c.query(`UPDATE stock_balances SET quantity=quantity-$4,updated_at=now() WHERE tenant_id=$1 AND outlet_id=$2 AND product_id=$3 RETURNING quantity`,[req.ctx.tenantId,req.ctx.outletId,it.product_id,n(it.qty)])).rows[0];await c.query(`INSERT INTO stock_ledger(tenant_id,outlet_id,product_id,type,qty_out,balance,reference,note,user_id) VALUES($1,$2,$3,'purchase_reversal',$4,$5,$6,'Hapus pembelian',$7)`,[req.ctx.tenantId,req.ctx.outletId,it.product_id,n(it.qty),bal.quantity,po.number,req.ctx.user.id])}await c.query(`DELETE FROM purchases WHERE id=$1`,[po.id]);return po.number});if(!number)return res.status(404).json({error:'Pembelian tidak ditemukan.'});await audit(req.ctx,'DELETE','purchase',number);res.json({ok:true})}catch(e){res.status(e.status||400).json({error:e.message})}});

async function saleWithItems(id,ctx){const r=(await pool.query(`SELECT s.*,COALESCE(json_agg(json_build_object('productId',si.product_id,'sku',si.sku,'name',si.name,'qty',si.qty,'price',si.price,'cost',si.cost,'subtotal',si.subtotal)) FILTER(WHERE si.id IS NOT NULL),'[]') items FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id AND si.tenant_id=s.tenant_id WHERE s.id=$1 AND s.tenant_id=$2 GROUP BY s.id`,[id,ctx.tenantId])).rows[0];return r?camelSale(r):null}
app.get('/api/sales',auth,async(req,res)=>{const rows=(await pool.query(`SELECT s.*,COALESCE(json_agg(json_build_object('productId',si.product_id,'sku',si.sku,'name',si.name,'qty',si.qty,'price',si.price,'cost',si.cost,'subtotal',si.subtotal)) FILTER(WHERE si.id IS NOT NULL),'[]') items FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id AND si.tenant_id=s.tenant_id WHERE s.tenant_id=$1 AND s.outlet_id=$2 GROUP BY s.id ORDER BY s.created_at DESC LIMIT 500`,[req.ctx.tenantId,req.ctx.outletId])).rows;res.json({items:rows.map(camelSale)})});
app.post('/api/pos/checkout',auth,activeSubscription,async(req,res)=>{const b=req.body||{};if(!Array.isArray(b.items)||!b.items.length)return res.status(400).json({error:'Keranjang kosong.'});try{const sid=await tx(async c=>{const invoice=code('INV');let subtotal=0,costTotal=0;const sale=(await c.query(`INSERT INTO sales(tenant_id,outlet_id,invoice,cashier_user_id,cashier_name,customer_id,payment_method,discount,paid) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[req.ctx.tenantId,req.ctx.outletId,invoice,req.ctx.user.id,req.ctx.user.name,b.customerId||null,b.paymentMethod||'cash',n(b.discount),n(b.paid)])).rows[0];for(const it of b.items){const p=(await c.query(`SELECT * FROM products WHERE id=$1 AND tenant_id=$2 AND active=true`,[it.productId,req.ctx.tenantId])).rows[0];if(!p)throw Object.assign(new Error('Produk pada keranjang tidak valid.'),{status:400});const qty=n(it.qty),price=n(it.price??p.price);const bal=(await c.query(`SELECT quantity FROM stock_balances WHERE tenant_id=$1 AND outlet_id=$2 AND product_id=$3 FOR UPDATE`,[req.ctx.tenantId,req.ctx.outletId,p.id])).rows[0]||{quantity:0};if(qty<=0||n(bal.quantity)<qty)throw Object.assign(new Error(`Stok ${p.name} tidak cukup.`),{status:400});const next=n(bal.quantity)-qty;await c.query(`UPDATE stock_balances SET quantity=$4,updated_at=now() WHERE tenant_id=$1 AND outlet_id=$2 AND product_id=$3`,[req.ctx.tenantId,req.ctx.outletId,p.id,next]);const sub=qty*price;subtotal+=sub;costTotal+=qty*n(p.cost);await c.query(`INSERT INTO sale_items(tenant_id,sale_id,product_id,sku,name,qty,price,cost,subtotal) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[req.ctx.tenantId,sale.id,p.id,p.sku,p.name,qty,price,n(p.cost),sub]);await c.query(`INSERT INTO stock_ledger(tenant_id,outlet_id,product_id,type,qty_out,balance,reference,note,user_id) VALUES($1,$2,$3,'sale',$4,$5,$6,'Penjualan POS',$7)`,[req.ctx.tenantId,req.ctx.outletId,p.id,qty,next,invoice,req.ctx.user.id])}const total=Math.max(0,subtotal-n(b.discount));if((b.paymentMethod||'cash')==='cash'&&n(b.paid)<total)throw Object.assign(new Error('Uang bayar kurang dari total.'),{status:400});let points=0;if(b.customerId){points=Math.floor(total/10000);await c.query(`UPDATE partners SET points=points+$3 WHERE id=$1 AND tenant_id=$2 AND type='customer'`,[b.customerId,req.ctx.tenantId,points])}await c.query(`UPDATE sales SET subtotal=$2,total=$3,cost_total=$4,points_earned=$5 WHERE id=$1`,[sale.id,subtotal,total,costTotal,points]);return sale.id});const out=await saleWithItems(sid,req.ctx);await audit(req.ctx,'CHECKOUT','sale',out.invoice);res.json(out)}catch(e){res.status(e.status||400).json({error:e.message})}});
app.put('/api/sales/:id',auth,activeSubscription,async(req,res)=>{const b=req.body||{};const out=await tx(async c=>{const s=(await c.query(`SELECT * FROM sales WHERE id=$1 AND tenant_id=$2 FOR UPDATE`,[req.params.id,req.ctx.tenantId])).rows[0];if(!s)return null;const nextCustomer=b.customerId??s.customer_id,nextMethod=b.paymentMethod??s.payment_method,nextDiscount=Math.max(0,n(b.discount??s.discount)),nextTotal=Math.max(0,n(s.subtotal)-nextDiscount),nextPaid=n(b.paid??s.paid);if(nextMethod==='cash'&&nextPaid<nextTotal)throw Object.assign(new Error('Uang bayar kurang dari total.'),{status:400});if(s.customer_id&&n(s.points_earned))await c.query(`UPDATE partners SET points=GREATEST(0,points-$3) WHERE id=$1 AND tenant_id=$2`,[s.customer_id,req.ctx.tenantId,n(s.points_earned)]);const points=nextCustomer?Math.floor(nextTotal/10000):0;if(nextCustomer)await c.query(`UPDATE partners SET points=points+$3 WHERE id=$1 AND tenant_id=$2`,[nextCustomer,req.ctx.tenantId,points]);await c.query(`UPDATE sales SET customer_id=$3,payment_method=$4,discount=$5,total=$6,paid=$7,points_earned=$8 WHERE id=$1 AND tenant_id=$2`,[s.id,req.ctx.tenantId,nextCustomer||null,nextMethod,nextDiscount,nextTotal,nextPaid,points]);return s.id});if(!out)return res.status(404).json({error:'Penjualan tidak ditemukan.'});const sale=await saleWithItems(out,req.ctx);await audit(req.ctx,'UPDATE','sale',sale.invoice);res.json(sale)});
app.delete('/api/sales/:id',auth,activeSubscription,async(req,res)=>{const invoice=await tx(async c=>{const s=(await c.query(`SELECT * FROM sales WHERE id=$1 AND tenant_id=$2 AND outlet_id=$3 FOR UPDATE`,[req.params.id,req.ctx.tenantId,req.ctx.outletId])).rows[0];if(!s)return null;const items=(await c.query(`SELECT * FROM sale_items WHERE sale_id=$1 AND tenant_id=$2`,[s.id,req.ctx.tenantId])).rows;for(const it of items){const bal=(await c.query(`INSERT INTO stock_balances(tenant_id,outlet_id,product_id,quantity) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,outlet_id,product_id) DO UPDATE SET quantity=stock_balances.quantity+$4,updated_at=now() RETURNING quantity`,[req.ctx.tenantId,req.ctx.outletId,it.product_id,n(it.qty)])).rows[0];await c.query(`INSERT INTO stock_ledger(tenant_id,outlet_id,product_id,type,qty_in,balance,reference,note,user_id) VALUES($1,$2,$3,'sale_reversal',$4,$5,$6,'Hapus penjualan',$7)`,[req.ctx.tenantId,req.ctx.outletId,it.product_id,n(it.qty),bal.quantity,s.invoice,req.ctx.user.id])}if(s.customer_id&&n(s.points_earned))await c.query(`UPDATE partners SET points=GREATEST(0,points-$3) WHERE id=$1 AND tenant_id=$2`,[s.customer_id,req.ctx.tenantId,n(s.points_earned)]);await c.query(`DELETE FROM sales WHERE id=$1`,[s.id]);return s.invoice});if(!invoice)return res.status(404).json({error:'Penjualan tidak ditemukan.'});await audit(req.ctx,'DELETE','sale',invoice);res.json({ok:true})});
app.post('/api/pos/hold',auth,activeSubscription,async(req,res)=>{const r=(await pool.query(`INSERT INTO held_sales(tenant_id,outlet_id,cashier_user_id,payload) VALUES($1,$2,$3,$4::jsonb) RETURNING id,created_at,payload`,[req.ctx.tenantId,req.ctx.outletId,req.ctx.user.id,JSON.stringify(req.body||{})])).rows[0];res.json({id:r.id,createdAt:r.created_at,...r.payload})});
app.get('/api/pos/held',auth,async(req,res)=>{const rows=(await pool.query(`SELECT id,created_at,payload FROM held_sales WHERE tenant_id=$1 AND outlet_id=$2 ORDER BY created_at DESC`,[req.ctx.tenantId,req.ctx.outletId])).rows;res.json({items:rows.map(x=>({id:x.id,createdAt:x.created_at,...x.payload}))})});
app.delete('/api/pos/held/:id',auth,async(req,res)=>{await pool.query(`DELETE FROM held_sales WHERE id=$1 AND tenant_id=$2 AND outlet_id=$3`,[req.params.id,req.ctx.tenantId,req.ctx.outletId]);res.json({ok:true})});

app.get('/api/expenses',auth,async(req,res)=>{const rows=(await pool.query(`SELECT * FROM expenses WHERE tenant_id=$1 AND (outlet_id=$2 OR outlet_id IS NULL) ORDER BY created_at DESC LIMIT 500`,[req.ctx.tenantId,req.ctx.outletId])).rows;res.json({items:rows.map(x=>({id:x.id,createdAt:x.created_at,category:x.category,description:x.description,amount:n(x.amount)}))})});
app.post('/api/expenses',auth,activeSubscription,async(req,res)=>{const r=(await pool.query(`INSERT INTO expenses(tenant_id,outlet_id,category,description,amount) VALUES($1,$2,$3,$4,$5) RETURNING *`,[req.ctx.tenantId,req.ctx.outletId,req.body.category||'Operasional',req.body.description||'',n(req.body.amount)])).rows[0];await audit(req.ctx,'CREATE','expense',r.description);res.json({id:r.id,createdAt:r.created_at,category:r.category,description:r.description,amount:n(r.amount)})});
app.put('/api/expenses/:id',auth,activeSubscription,async(req,res)=>{const r=(await pool.query(`UPDATE expenses SET category=COALESCE($3,category),description=COALESCE($4,description),amount=COALESCE($5,amount) WHERE id=$1 AND tenant_id=$2 RETURNING *`,[req.params.id,req.ctx.tenantId,req.body.category??null,req.body.description??null,req.body.amount==null?null:Math.max(0,n(req.body.amount))])).rows[0];if(!r)return res.status(404).json({error:'Biaya tidak ditemukan.'});await audit(req.ctx,'UPDATE','expense',r.description);res.json({id:r.id,createdAt:r.created_at,category:r.category,description:r.description,amount:n(r.amount)})});
app.delete('/api/expenses/:id',auth,activeSubscription,async(req,res)=>{const r=(await pool.query(`DELETE FROM expenses WHERE id=$1 AND tenant_id=$2 RETURNING description`,[req.params.id,req.ctx.tenantId])).rows[0];if(!r)return res.status(404).json({error:'Biaya tidak ditemukan.'});await audit(req.ctx,'DELETE','expense',r.description);res.json({ok:true})});

app.get('/api/dashboard',auth,async(req,res)=>{const t=req.ctx.tenantId,o=req.ctx.outletId;const [stats,low,recent,daily]=await Promise.all([
 pool.query(`SELECT COALESCE(SUM(total) FILTER(WHERE created_at::date=current_date),0) total_today,COUNT(*) FILTER(WHERE created_at::date=current_date) transactions_today,COALESCE(SUM(total) FILTER(WHERE date_trunc('month',created_at)=date_trunc('month',now())),0) total_month FROM sales WHERE tenant_id=$1 AND outlet_id=$2`,[t,o]),
 pool.query(`SELECT p.*,COALESCE(sb.quantity,0) stock FROM products p LEFT JOIN stock_balances sb ON sb.product_id=p.id AND sb.tenant_id=p.tenant_id AND sb.outlet_id=$2 WHERE p.tenant_id=$1 AND p.active=true AND COALESCE(sb.quantity,0)<=p.min_stock ORDER BY stock ASC LIMIT 50`,[t,o]),
 pool.query(`SELECT * FROM sales WHERE tenant_id=$1 AND outlet_id=$2 ORDER BY created_at DESC LIMIT 8`,[t,o]),
 pool.query(`SELECT d::date date,COALESCE(SUM(s.total),0) total FROM generate_series(current_date-6,current_date,'1 day') d LEFT JOIN sales s ON s.tenant_id=$1 AND s.outlet_id=$2 AND s.created_at::date=d::date GROUP BY d ORDER BY d`,[t,o])]);
 const productCount=n((await pool.query(`SELECT COUNT(*) c FROM products WHERE tenant_id=$1 AND active=true`,[t])).rows[0].c);const st=stats.rows[0];res.json({totalToday:n(st.total_today),transactionsToday:n(st.transactions_today),totalMonth:n(st.total_month),products:productCount,lowStock:low.rows.map(camelProduct),recent:recent.rows.map(camelSale),daily:daily.rows.map(x=>({date:x.date,total:n(x.total)}))})});

app.get('/api/reports/summary',auth,async(req,res)=>{const from=String(req.query.from||'1900-01-01'),to=String(req.query.to||'2999-12-31'),t=req.ctx.tenantId,o=req.ctx.outletId;const sales=(await pool.query(`SELECT s.*,COALESCE(json_agg(json_build_object('productId',si.product_id,'name',si.name,'qty',si.qty,'subtotal',si.subtotal)) FILTER(WHERE si.id IS NOT NULL),'[]') items FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id AND si.tenant_id=s.tenant_id WHERE s.tenant_id=$1 AND s.outlet_id=$2 AND s.created_at::date BETWEEN $3::date AND $4::date GROUP BY s.id ORDER BY s.created_at DESC`,[t,o,from,to])).rows.map(camelSale);const expenses=(await pool.query(`SELECT amount FROM expenses WHERE tenant_id=$1 AND (outlet_id=$2 OR outlet_id IS NULL) AND created_at::date BETWEEN $3::date AND $4::date`,[t,o,from,to])).rows;const revenue=sales.reduce((a,b)=>a+b.total,0),cogs=sales.reduce((a,b)=>a+b.costTotal,0),expense=expenses.reduce((a,b)=>a+n(b.amount),0),byProduct={};for(const s of sales)for(const i of s.items){byProduct[i.productId]??={name:i.name,qty:0,revenue:0};byProduct[i.productId].qty+=n(i.qty);byProduct[i.productId].revenue+=n(i.subtotal)}res.json({revenue,cogs,grossProfit:revenue-cogs,expenses:expense,netProfit:revenue-cogs-expense,transactions:sales.length,topProducts:Object.values(byProduct).sort((a,b)=>b.qty-a.qty).slice(0,10),sales})});

app.get('/api/users',auth,async(req,res)=>{const rows=(await pool.query(`SELECT u.id,u.name,u.username,u.email,u.active,u.created_at,r.name role,tu.default_outlet_id FROM tenant_users tu JOIN users u ON u.id=tu.user_id LEFT JOIN roles r ON r.id=tu.role_id WHERE tu.tenant_id=$1 ORDER BY u.created_at`,[req.ctx.tenantId])).rows;res.json({items:rows.map(x=>({id:x.id,name:x.name,username:x.username,email:x.email||'',role:x.role,active:x.active,createdAt:x.created_at,defaultOutletId:x.default_outlet_id}))})});
app.post('/api/users',auth,activeSubscription,async(req,res)=>{const b=req.body||{};try{const out=await tx(async c=>{const plan=(await c.query(`SELECT sp.max_users FROM subscriptions s JOIN subscription_plans sp ON sp.id=s.plan_id WHERE s.tenant_id=$1 ORDER BY s.created_at DESC LIMIT 1`,[req.ctx.tenantId])).rows[0];const count=n((await c.query(`SELECT COUNT(*) c FROM tenant_users WHERE tenant_id=$1 AND active=true`,[req.ctx.tenantId])).rows[0].c);if(plan&&count>=plan.max_users)throw Object.assign(new Error(`Batas user paket saat ini adalah ${plan.max_users}.`),{status:409});if((await c.query(`SELECT 1 FROM users WHERE username=$1`,[b.username])).rowCount)throw Object.assign(new Error('Username sudah digunakan.'),{status:409});const hash=await bcrypt.hash(b.password||'123456',10);const u=(await c.query(`INSERT INTO users(name,username,email,password_hash) VALUES($1,$2,$3,$4) RETURNING *`,[b.name||b.username,b.username,b.email||null,hash])).rows[0];const role=(await c.query(`SELECT id,name FROM roles WHERE tenant_id=$1 AND name=$2`,[req.ctx.tenantId,b.role||'Kasir'])).rows[0]||(await c.query(`SELECT id,name FROM roles WHERE tenant_id=$1 ORDER BY name LIMIT 1`,[req.ctx.tenantId])).rows[0];await c.query(`INSERT INTO tenant_users(tenant_id,user_id,role_id,default_outlet_id) VALUES($1,$2,$3,$4)`,[req.ctx.tenantId,u.id,role.id,b.outletId||req.ctx.outletId]);return {...u,role:role.name}});await audit(req.ctx,'CREATE','user',out.username);res.json({id:out.id,name:out.name,username:out.username,role:out.role,active:out.active,createdAt:out.created_at})}catch(e){res.status(e.status||400).json({error:e.message})}});
app.put('/api/users/:id',auth,activeSubscription,async(req,res)=>{const b=req.body||{};const out=await tx(async c=>{const u=(await c.query(`SELECT u.* FROM users u JOIN tenant_users tu ON tu.user_id=u.id WHERE u.id=$1 AND tu.tenant_id=$2`,[req.params.id,req.ctx.tenantId])).rows[0];if(!u)return null;if(b.password)await c.query(`UPDATE users SET password_hash=$2 WHERE id=$1`,[u.id,await bcrypt.hash(b.password,10)]);await c.query(`UPDATE users SET name=$2,active=$3 WHERE id=$1`,[u.id,b.name??u.name,b.active??u.active]);if(b.role){const role=(await c.query(`SELECT id FROM roles WHERE tenant_id=$1 AND name=$2`,[req.ctx.tenantId,b.role])).rows[0];if(role)await c.query(`UPDATE tenant_users SET role_id=$3 WHERE tenant_id=$1 AND user_id=$2`,[req.ctx.tenantId,u.id,role.id])}return u});if(!out)return res.status(404).json({error:'User tidak ditemukan.'});await audit(req.ctx,'UPDATE','user',out.username);res.json({ok:true})});

app.get('/api/settings',auth,async(req,res)=>{const s=(await pool.query(`SELECT * FROM tenant_settings WHERE tenant_id=$1`,[req.ctx.tenantId])).rows[0];res.json({companyName:s.company_name,address:s.address,phone:s.phone,email:s.email,taxRate:n(s.tax_rate),receiptFooter:s.receipt_footer,currency:s.currency,lowStockThreshold:n(s.low_stock_threshold),tenantName:req.ctx.tenantName,outletName:req.ctx.outletName,subscription:req.ctx.subscription})});
app.put('/api/settings',auth,activeSubscription,async(req,res)=>{const b=req.body||{};const s=(await pool.query(`UPDATE tenant_settings SET company_name=COALESCE($2,company_name),address=COALESCE($3,address),phone=COALESCE($4,phone),email=COALESCE($5,email),tax_rate=COALESCE($6,tax_rate),receipt_footer=COALESCE($7,receipt_footer),low_stock_threshold=COALESCE($8,low_stock_threshold),updated_at=now() WHERE tenant_id=$1 RETURNING *`,[req.ctx.tenantId,b.companyName??null,b.address??null,b.phone??null,b.email??null,b.taxRate==null?null:n(b.taxRate),b.receiptFooter??null,b.lowStockThreshold==null?null:n(b.lowStockThreshold)])).rows[0];await pool.query(`UPDATE tenants SET name=$2,updated_at=now() WHERE id=$1`,[req.ctx.tenantId,s.company_name]);await audit(req.ctx,'UPDATE','settings','company');res.json({companyName:s.company_name,address:s.address,phone:s.phone,email:s.email,taxRate:n(s.tax_rate),receiptFooter:s.receipt_footer,lowStockThreshold:n(s.low_stock_threshold)})});
app.get('/api/audit',auth,async(req,res)=>{const rows=(await pool.query(`SELECT at,username,action,entity,detail FROM audit_logs WHERE tenant_id=$1 ORDER BY at DESC LIMIT 300`,[req.ctx.tenantId])).rows;res.json({items:rows.map(x=>({at:x.at,user:x.username,action:x.action,entity:x.entity,detail:x.detail}))})});

app.get('/api/subscription',auth,async(req,res)=>{res.json(req.ctx.subscription||{})});
app.get('/api/platform/tenants',auth,platformAdmin,async(req,res)=>{const rows=(await pool.query(`SELECT t.id,t.code,t.name,t.status,t.created_at,sp.name plan,s.status subscription_status,s.expires_at,(SELECT COUNT(*) FROM tenant_users tu WHERE tu.tenant_id=t.id AND tu.active) users,(SELECT COUNT(*) FROM outlets o WHERE o.tenant_id=t.id AND o.active) outlets FROM tenants t LEFT JOIN LATERAL(SELECT * FROM subscriptions s2 WHERE s2.tenant_id=t.id ORDER BY created_at DESC LIMIT 1)s ON true LEFT JOIN subscription_plans sp ON sp.id=s.plan_id ORDER BY t.created_at DESC`)).rows;res.json({items:rows})});
app.get('/api/platform/summary',auth,platformAdmin,async(req,res)=>{const [tenants,active,users,mrr]=await Promise.all([pool.query(`SELECT COUNT(*) c FROM tenants`),pool.query(`SELECT COUNT(*) c FROM tenants WHERE status='active'`),pool.query(`SELECT COUNT(*) c FROM users WHERE active=true`),pool.query(`SELECT COALESCE(SUM(sp.price_monthly),0) mrr FROM subscriptions s JOIN subscription_plans sp ON sp.id=s.plan_id WHERE s.status='active' AND s.expires_at>now()`)]);res.json({tenants:n(tenants.rows[0].c),activeTenants:n(active.rows[0].c),users:n(users.rows[0].c),mrr:n(mrr.rows[0].mrr)})});
app.put('/api/platform/tenants/:id/status',auth,platformAdmin,async(req,res)=>{const status=String(req.body.status||'active');if(!['active','suspended','closed'].includes(status))return res.status(400).json({error:'Status tidak valid.'});const r=await pool.query(`UPDATE tenants SET status=$2,updated_at=now() WHERE id=$1 RETURNING id,name,status`,[req.params.id,status]);if(!r.rowCount)return res.status(404).json({error:'Tenant tidak ditemukan.'});res.json(r.rows[0])});

app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Terjadi kesalahan pada server.'})});
app.listen(PORT,'0.0.0.0',()=>console.log(`${APP_NAME} SaaS v2.0 running on port ${PORT}`));
